In [1]:
import sklearn
import joblib

print("scikit-learn version:", sklearn.__version__)
print("joblib loaded successfully")

scikit-learn version: 1.5.1
joblib loaded successfully

In [4]:
!pip install scikit-learn==1.7.2

Requirement already satisfied: scikit-learn==1.7.2 in c:\users\bushrah elaf\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\bushrah elaf\anaconda3\lib\site-packages (from scikit-learn==1.7.2) (1.26.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\bushrah elaf\anaconda3\lib\site-packages (from scikit-learn==1.7.2) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\bushrah elaf\anaconda3\lib\site-packages (from scikit-learn==1.7.2) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\bushrah elaf\anaconda3\lib\site-packages (from scikit-learn==1.7.2) (3.5.0)

In [1]:
import sklearn
print(sklearn.__version__)

1.7.2

In [3]:
#loading trained model
import joblib

model = joblib.load("C:/Users/Bushrah Elaf/OneDrive/github/ML-Lab-Final-Group-3/models/spam_classifier.pkl")

print("Model loaded successfully!")

Model loaded successfully!

C:\Users\Bushrah Elaf\anaconda3\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator MultinomialNB from version 1.6.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [4]:
vectorizer = joblib.load("C:/Users/Bushrah Elaf/OneDrive/github/ML-Lab-Final-Group-3/data/processed/tfidf_vectorizer.joblib")

print("TF-IDF vectorizer loaded successfully!")

TF-IDF vectorizer loaded successfully!

In [5]:
message = "Congratulations! You have won a free prize!"

In [6]:
message_tfidf = vectorizer.transform([message])

print(message_tfidf.shape)

(1, 3000)

In [7]:
prediction = model.predict(message_tfidf)

print("Prediction:", prediction[0])

Prediction: 1

In [8]:
print(model.classes_)

[0 1]

In [9]:
print(model.predict_proba(message_tfidf))

[[0.00269383 0.99730617]]

In [10]:
def predict_message(message):
    message_tfidf = vectorizer.transform([message])
    
    prediction = model.predict(message_tfidf)[0]
    probabilities = model.predict_proba(message_tfidf)[0]
    
    if prediction == 1:
        label = "Spam"
    else:
        label = "Ham"
    
    spam_probability = probabilities[1]
    
    return label, spam_probability

In [11]:
label, spam_probability = predict_message(
    "Congratulations! You have won a free prize!"
)

print("Prediction:", label)
print("Spam probability:", spam_probability)

Prediction: Spam
Spam probability: 0.9973061683517527

In [12]:
label, spam_probability = predict_message(
    "Hey, are we still meeting for lunch tomorrow?"
)

print("Prediction:", label)
print("Spam probability:", spam_probability)

Prediction: Ham
Spam probability: 0.000702332750785671

In [13]:
test_messages = [
    "Free entry in a weekly competition! Text WIN to 80000 now!",
    "Can you send me the assignment notes?",
    "Congratulations, you have won a cash prize!",
    "I'll call you when I reach home."
]

for message in test_messages:
    label, spam_probability = predict_message(message)
    
    print("Message:", message)
    print("Prediction:", label)
    print("Spam probability:", round(spam_probability, 4))
    print("-" * 50)

Message: Free entry in a weekly competition! Text WIN to 80000 now!
Prediction: Spam
Spam probability: 0.9933
--------------------------------------------------
Message: Can you send me the assignment notes?
Prediction: Ham
Spam probability: 0.1524
--------------------------------------------------
Message: Congratulations, you have won a cash prize!
Prediction: Spam
Spam probability: 0.9975
--------------------------------------------------
Message: I'll call you when I reach home.
Prediction: Ham
Spam probability: 0.0037
--------------------------------------------------

In [14]:
test_messages = [
    "Free entry in a weekly competition! Text WIN to 80000 now!",
    "Can you send me the assignment notes?",
    "Congratulations, you have won a cash prize!",
    "I'll call you when I reach home.",
    "URGENT! Claim your free reward now!"
]

print(test_messages)

['Free entry in a weekly competition! Text WIN to 80000 now!', 'Can you send me the assignment notes?', 'Congratulations, you have won a cash prize!', "I'll call you when I reach home.", 'URGENT! Claim your free reward now!']

In [15]:
results = []

for message in test_messages:
    label, spam_probability = predict_message(message)
    
    results.append({
        "message": message,
        "prediction": label,
        "spam_probability": spam_probability
    })

results

[{'message': 'Free entry in a weekly competition! Text WIN to 80000 now!',
  'prediction': 'Spam',
  'spam_probability': 0.9932980269547101},
 {'message': 'Can you send me the assignment notes?',
  'prediction': 'Ham',
  'spam_probability': 0.15244418847889712},
 {'message': 'Congratulations, you have won a cash prize!',
  'prediction': 'Spam',
  'spam_probability': 0.9975066277175937},
 {'message': "I'll call you when I reach home.",
  'prediction': 'Ham',
  'spam_probability': 0.003693869772331735},
 {'message': 'URGENT! Claim your free reward now!',
  'prediction': 'Spam',
  'spam_probability': 0.9981989608601124}]

In [16]:
import pandas as pd

results_df = pd.DataFrame(results)

results_df

,message,prediction,spam_probability
0,Free entry in a weekly competition! Text WIN t...,Spam,0.993298
1,Can you send me the assignment notes?,Ham,0.152444
2,"Congratulations, you have won a cash prize!",Spam,0.997507
3,I'll call you when I reach home.,Ham,0.003694
4,URGENT! Claim your free reward now!,Spam,0.998199

In [19]:
results_df.to_csv("C:/Users/Bushrah Elaf/OneDrive/github/ML-Lab-Final-Group-3/outputs", index=False)

print("Predictions saved successfully!")

PermissionError: [Errno 13] Permission denied: 'C:/Users/Bushrah Elaf/OneDrive/github/ML-Lab-Final-Group-3/outputs'

In [20]:
results_df.to_csv(
    "C:/Users/Bushrah Elaf/OneDrive/github/ML-Lab-Final-Group-3/outputs/ml_predictions.csv",
    index=False
)

print("Predictions saved successfully!")

Predictions saved successfully!

In [21]:
results_df

,message,prediction,spam_probability
0,Free entry in a weekly competition! Text WIN t...,Spam,0.993298
1,Can you send me the assignment notes?,Ham,0.152444
2,"Congratulations, you have won a cash prize!",Spam,0.997507
3,I'll call you when I reach home.,Ham,0.003694
4,URGENT! Claim your free reward now!,Spam,0.998199